// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademico.Api.Server.Data;

#nullable disable

namespace SistemaAcademico.Api.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.Exame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preparo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exames");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.ResultadoExame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArquivoResultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataLiberacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SolicitacaoExameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoExameId")
                        .IsUnique();

                    b.ToTable("ResultadosExames");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.SolicitacaoExame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicoSolicitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExameId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Protocolo")
                        .IsUnique();

                    b.ToTable("SolicitacoesExames");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.ResultadoExame", b =>
                {
                    b.HasOne("SistemaAcademico.Api.Server.Models.SolicitacaoExame", "SolicitacaoExame")
                        .WithOne("Resultado")
                        .HasForeignKey("SistemaAcademico.Api.Server.Models.ResultadoExame", "SolicitacaoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoExame");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.SolicitacaoExame", b =>
                {
                    b.HasOne("SistemaAcademico.Api.Server.Models.Exame", "Exame")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("ExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademico.Api.Server.Models.Paciente", "Paciente")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exame");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.Exame", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.Paciente", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("SistemaAcademico.Api.Server.Models.SolicitacaoExame", b =>
                {
                    b.Navigation("Resultado");
                });
#pragma warning restore 612, 618
        }
    }
}
